### PR TITLE
Enable proxy support for HTTPGET Tasks.

### PR DESCRIPTION
**Pull request by drupol**
Now that support for proxy has been included in HttpGet Task (see: https://github.com/phingofficial/phing/pull/70), we can add a new option in build.xml to enable the proxy.

Without this, I cannot get it working in my company and I suppose that I'm not the only one.

### CODE REVIEW

**Comment by kasperg** [comment]
Thanks for the contribution!

I'll merge this when proxy support for the HttpGet task is included with a stable Phing release.

**Comment by drupol** [comment]
Ok :-) thanks !

**Comment by drupol** [comment]
Phing 2.4.11 is released yesterday and it includes the changes for the httpget proxy.

Can you commit this ?

Thanks !

**Comment by kasperg** [comment]
I'd like to add this change but the pull request now also contains changes regarding rewritebase covered in [PR #13](https://github.com/reload/phing-drupal-template/pull/13).

Could you create a separate branch for the proxy feature and update the pull request accordingly?

**Pull request closed without merging**
