### PR TITLE
RewriteBase modification after make.

### PR DESCRIPTION
**Pull request by drupol**
Enable modification of the RewriteBase directive through a property.

### CODE REVIEW

**Comment by kasperg** [comment]
Could you explain in which situations this is needed?

**Comment by drupol** [comment]
Hey Kasperg,

This is needed when you install Drupal in a subdirectory, for ex: `http://localhost/sites/drupal7`
If you do not modify the RewriteBase, in some case, Drupal will redirect request to `/` instead of `/sites/drupal7`.

See documentation about this directly from drupal.org at [this address](http://drupalcode.org/project/drupal.git/blob/refs/heads/7.x:/.htaccess#l90).

**Comment by kasperg** [comment]
Thanks for the explanation.

I'd like to get this in but I have a few stylistic suggestions:
1. The `RewriteBase` property should follow the same style as the rest of the project i.e. lower case
2. As the feature only works when using `drush_make` I think this should be reflected in the code. The definition of the variable should be below the other `project.make` properties and properly also renamed to `project.make.rewritebase`. Otherwise consider making this an separate target in the build.
3. Please add some inline documentation describing what this part of the build deals with. The comments are extracted when generating [the documentation](http://reload.github.com/phing-drupal-template/).

**Comment by kasperg** [comment]
Great! Merged.

**Pull request merged**
